name: Lint

on: [pull_request]

jobs:
  lint:
    name: Lint & Check Type
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Run ESLint
        uses: tj-actions/eslint-changed-files@v19.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          config_path: ".eslintrc.cjs"

      - name: Check types
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-pr-review
          # See https://github.com/EPMatt/reviewdog-action-tsc#why-cant-i-see-the-results &
          # https://github.com/reviewdog/reviewdog#nofilter
          filter_mode: nofilter
          fail_on_error: true

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v2
